project:
  type: website

website:
  title: "Data Analytics for Immersive Environments"
  navbar:
    left:
      - text: "Home" 
        href: index.qmd
      - text: "Part A - SQL" 
        href: partA_SQL.qmd
      - text: "Part B - Linear Regression" 
        href: partA_Regression.qmd
      - text: "Part D - Technology Exploration" 
        href: partD_TechExploration.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    code-summary: "Show Code"
    page-layout: full
    smooth-scroll: true

editor: visual

