project:
  type: website

website:
  title: "Data Analytics for Immersive Environments"
  navbar:
    left:
      - text: "Home" 
        href: index.qmd
      - text: "SQL" 
        href: partA_SQL.qmd
      - text: "Linear Regression" 
        href: partB_Regression.qmd
      - text: "Technology Exploration" 
        href: partD_TechExploration.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    number-sections: false
    code-summary: "Show Code"
    page-layout: full
    smooth-scroll: true

editor: visual

